apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: apps
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR-GH-USER>/app-of-apps-repo.git
    targetRevision: HEAD
    path: apps                 # LOOK HERE
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd          # parent doesn’t create resources itself
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
